<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="47016" started-at="2018-03-05T05:11:17Z" finished-at="2018-03-05T05:12:04Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="47016" started-at="2018-03-05T05:11:17Z" finished-at="2018-03-05T05:12:04Z">
      <class name="com.iel.automation.testcases.LoginTest">
        <test-method status="PASS" signature="reportSetup()[pri:0, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="reportSetup" is-config="true" duration-ms="171" started-at="2018-03-05T00:11:17Z" finished-at="2018-03-05T00:11:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportSetup -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="setUp" is-config="true" duration-ms="33492" started-at="2018-03-05T00:11:17Z" finished-at="2018-03-05T00:11:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.iel.automation.testcases.LoginTest.verifyLogin() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLogin()[pri:1, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="verifyLogin" duration-ms="467" started-at="2018-03-05T00:11:51Z" description="Verify Login for Valid Credentials" finished-at="2018-03-05T00:11:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="getResult" is-config="true" duration-ms="1294" started-at="2018-03-05T00:11:51Z" finished-at="2018-03-05T00:11:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogin status=SUCCESS method=LoginTest.verifyLogin()[pri:1, instance:com.iel.automation.testcases.LoginTest@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="setUp(java.lang.reflect.Method)[pri:0, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="setUp" is-config="true" duration-ms="9859" started-at="2018-03-05T00:11:53Z" finished-at="2018-03-05T00:12:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.iel.automation.testcases.LoginTest.verifyInvalidLogin() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyInvalidLogin()[pri:2, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="verifyInvalidLogin" duration-ms="477" started-at="2018-03-05T00:12:03Z" description="Verify Login for InValid Credentials" finished-at="2018-03-05T00:12:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Username or Password is incorrect expected [http://staging.inspiredlms.com/user/master.aspx] but found [https://ilmsdevqa.inspiredlms.com/admin/login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Username or Password is incorrect expected [http://staging.inspiredlms.com/user/master.aspx] but found [https://ilmsdevqa.inspiredlms.com/admin/login]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.iel.automation.pages.HomePage.verfiyLogin(HomePage.java:61)
	at com.iel.automation.testcases.LoginTest.verifyInvalidLogin(LoginTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidLogin -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.iel.automation.testcases.LoginTest@e4487af]" name="getResult" is-config="true" duration-ms="1381" started-at="2018-03-05T00:12:03Z" finished-at="2018-03-05T00:12:04Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyInvalidLogin status=FAILURE method=LoginTest.verifyInvalidLogin()[pri:2, instance:com.iel.automation.testcases.LoginTest@e4487af] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- com.iel.automation.testcases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
